### ISSUE TITLE
Node versions supported

### ISSUE THREAD

**Issue by millette** [brainsiq/hapi-boom-decorators#39]
With the recent change <https://github.com/brainsiq/hapi-boom-decorators/commit/02fa06af1f37114f04cc82eab78e3923df8edd86>, Node 4.x isn't supported anymore.

Is there a way to keep support for Node 4 (the "..." argument is failing)?

Otherwise, please update the package.json engine field and maybe consider this a major (breaking) change?

**Comment by brainsiq** [comment]
Yes I should be able to use apply instead of the spread operator.

**Comment by brainsiq** [comment]
I've published v2.2.1 which should fix that for you.

**Comment by millette** [comment]
Awesome, thanks a lot!
